#端口
server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  mail:
    host: smtp.163.com
    username: fanshuye1304@163.com
    password: fanshuye1304
  freemarker:
    suffix: .ftl
    request-context-attribute: request
    charset: UTF-8
  aop:
    proxy-target-class: true

# Swagger界面内容配置
swagger:
  title: CHAPTER API接口文档
  description: CHAPTER Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://blog.sh123.top
  contact:
    name: CHAPTER
    url: http://blog.sh123.top
    email: 840865635@qq.com

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.org.entity
  typeEnumsPackage: com.org.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 1
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    # capital-mode: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: -1
    logic-not-delete-value: 0
    mybatis-plus-global-config-sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#日志
logback:
  logdir: logs/
  appname: chapter

#文件上传路径
file-upload-path: E:/test
